### ISSUE TITLE
Inconsistency between predicate in bt_example.pddl and the tutorial

### ISSUE THREAD

**Issue by tammerb** [IntelligentRoboticsLabs/ros2_planning_system_examples#16]
In `/plansys2_ws/src/ros2_planning_system_examples/plansys2_bt_example/pddl/bt_example.pddl` the predicate is `(piece_is_sterwheel ?p - piece)`, but in the [tutorial](https://intelligentroboticslab.gsyc.urjc.es/ros2_planning_system.github.io/tutorials/docs/bt_actions.html#running-the-example) the command to enter in the plansys2 terminal is `> set predicate (piece_is_steering_wheel steering_wheel_1)`, which returns an error.

Note: This issue is also posted in the website repo.

**Comment by fmrico** [comment]
Hi @tammerb 

Yes!! I think I erroneously committed predicates like `(piece_is_sterwheel ?p - piece)`.

I will fix it as soon as I can. Maybe you would like to make a PR?

Thanks anyway!!

**Comment by tammerb** [comment]
PR created.
