### ISSUE TITLE
Build failed with Plansys2 from APT

### ISSUE THREAD

**Issue by eborghi10** [IntelligentRoboticsLabs/ros2_planning_system_examples#23]
Installing Plansys2 from APT (`sudo apt-get install -y ros-foxy-plansys2*`) and this package from source (`foxy-devel` branch) pops out a compilation error:

```
--- stderr: plansys2_patrol_navigation_example
/home/robotica/colcon_ws/src/amr/ros2_planning_system_examples/plansys2_patrol_navigation_example/
src/patrolling_controller_node.cpp:15:10: fatal e
rror: plansys2_pddl_parser/Utils.h: No such file 
or directory 
   15 | #include <plansys2_pddl_parser/Utils.h>
```

Checking the include directory where `plansys2_pddl_parser` is installed:

```
$ /opt/ros/foxy/include/plansys2_pddl_parser$ ls | grep Utils.h

```

The file is not being installed. According to the `package.xml`, the version is `1.0.9`. Should the foxy package be updated?

**Comment by fmrico** [comment]
Hi @eborghi10 

I will check it tomorrow, and probably I should do a new release for foxy. Meanwhile, use PlanSys2 from sources.

Sorry :A
Francisco

**Comment by fmrico** [comment]
Hi @eborghi10 

I have just checked that version 1.0.10 is scheduled for the next Foxy sync: https://github.com/ros/rosdistro/pull/30107

The missing file is included in this package: https://github.com/IntelligentRoboticsLabs/ros2_planning_system-release/releases/tag/release%2Ffoxy%2Fplansys2_pddl_parser%2F1.0.10-1

I am not sure what could happen, but it seems to be fixed soon. 

I will not close this issue until the next sync and your confirmation that it is fixed there.

Please, use sources meanwhile. Sorry for the inconvenience.
Francisco
